[package]
name = "hunk"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
dirs = "6.0"
git2 = { version = "0.20", features = ["https", "ssh"] }
gpui = { package = "gpui", version = "*" }
gpui-component = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
syntect = "5.3"
