[package]
name = "hunk"
version = "0.1.0"
edition = "2024"

[package.metadata.bundle]
name = "Hunk"
identifier = "com.prodata.hunk"
short_description = "Fast git diff viewer."
long_description = "A fast, simple git diff viewer built with GPUI."
category = "public.app-category.developer-tools"
icon = ["assets/icons/Hunk.icns"]

[dependencies]
anyhow = "1.0"
dirs = "6.0"
git2 = { version = "0.20", features = ["https", "ssh"] }
gpui = { package = "gpui", version = "*" }
gpui-component = { version = "0.5.1", features = ["tree-sitter-languages"] }
gpui-component-assets = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
syntect = "5.3"
